---
- hosts: all
  become: true

  pre_tasks: #Task 1.3 

    - name: Install updates (CentOS)
      dnf:
         #update_only: yes
         #update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Install updates (Ubuntu)
      apt:
          #upgrade: dist
          #update_cache: yes
      when: ansible_distribution == "Ubuntu"

  tasks:  #Task 1.1: Targetting Specific Nodes

    - name: Install apache and php for Ubuntu servers
      apt:
         name:
            - apache2
            - libapache2-mod-php
         state: latest
         update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install apache and php for CentOS servers
      dnf:
          name:
            - httpd
            - php
          state: latest
      when: ansible_distribution == "CentOS"

- hosts: db_servers  #Task 1.4: Targetting Specific Nodes
  become: true
  tasks:

    - name: Install mariadb package (CentOs)
      yum:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Mariadb- Restarting/Enabling
      service:
          name: mariadb-server
          state: restarted
          enabled: true
      when: ansible_distribution == "CentOS"

    - name: Install mariadb package (Ubuntu)
      apt:
          name: mariadb-server
          state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers #Task 1.6
  become: true
  tasks:

    - name: Install samba package
      package: 
          name: samba
          state: latest
