    - name: Install mariadb package (CentOs)
      tags: centos, db, mariadb
      yum:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Mariadb- Restarting/Enabling
      service:
          name: mariadb-server
          state: started
          enabled: true
      when: ansible_distribution == "CentOS"

    - name: Install mariadb package (Ubuntu)
      tags: db, mariadb, ubuntu
      apt:
          name: mariadb-server
          state: latest
      when: ansible_distribution == "Ubuntu"